# Caller of this workflow script need secret "PAT_INFRA_RP_EKS_APPLY_VERSION", which contains PAT (Personal Access Token) “apply-app-version-token”.
# This one is needed to be allowed to call this script.
#
# ATTENTION: The PET will expire 2025-06-24, and has to be updated before that. Proceed following steps then:
# 1. select fine-grained personal access token "update-doc-rp-api-token" in https://github.com/settings/tokens?type=beta and regenerate token (or create a new one with resource owner "moost-io" + "Content" repository access "only selected repositories: doc-rp-api")
# 2. update secret PAT_INFRA_RP_EKS_APPLY_VERSION here: https://github.com/organizations/moost-io/settings/secrets/actions/PAT_DOC_RP_API_UPDATE_PUBLIC_API
# 3. set a reminder in your calendar ca. 3 weeks before token expires.
name: Update Public API
run-name: Change version of ${{ github.event.client_payload.appName }} to ${{ github.event.client_payload.appVersion }} on ${{ github.event.client_payload.appEnv }} by @${{ github.actor }}
on:
  repository_dispatch:
    types:
    - update-public-api
jobs:
  apply-app-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update App Version on Git
        env:
          VALUE_FILE: "values-${{ github.event.client_payload.appEnv }}.yaml"
          MANIFEST_FILE: "apply/${{ github.event.client_payload.appEnv }}/manifest.yaml"
        run: |
          cd apps/${{ github.event.client_payload.appDomain }}/${{ github.event.client_payload.appName }}
          sed -i 's/  tag: "[^"]*"/  tag: "${{ github.event.client_payload.appVersion }}"/g' $VALUE_FILE
          helm template . -f "values.yaml" -f "$VALUE_FILE" > $MANIFEST_FILE
          git add $VALUE_FILE
          git add $MANIFEST_FILE
          set +e  # Grep succeeds with nonzero exit codes to show results.
          git status | egrep '(modified|new file):' | grep $VALUE_FILE
          if [ $? -eq 0 ]
          then
            set -e
            git config --global user.name "GitHub-CI-Workflow"
            git config --global user.email "GitHub.CI.Workflow@moost.io"
            git commit -m "Change version of ${{ github.event.client_payload.appName }} to ${{ github.event.client_payload.appVersion }} on ${{ github.event.client_payload.appEnv }}"
            git push
          else
            set -e
            echo "No change"
          fi

      - name: ArgoCD Login
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          cluster_name: ${{ env.CLUSTER_NAME }}
          args: --namespace=argocd exec deploy/argocd-server -- bash -c "argocd login ${{ env.ARGOCD_DOMAIN }} --username admin --password ${{ env.ARGOCD_PWD }}

      - name: ArgoCD App Sync
        uses: ianbelcher/eks-kubectl-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          cluster_name: ${{ env.CLUSTER_NAME }}
          args: --namespace=argocd exec deploy/argocd-server -- bash -c "argocd app sync ${{ github.event.client_payload.appName }}-app"
